<?php

namespace Tests\Unit;

use App\Models\Category;
use App\Models\Subcategory;
use Eris\Generator;
use Eris\TestTrait;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

/**
 * Property-Based Test for Category Hierarchy Management
 * Feature: marketplace-platform, Property 7: Category Hierarchy Management
 * Validates: Requirements 4.1, 4.2, 4.3
 */
class CategoryHierarchyPropertyTest extends TestCase
{
    use RefreshDatabase, TestTrait;

    /**
     * Property 7: Category Hierarchy Management
     * For any category or subcategory creation, the system should generate unique slugs 
     * and maintain proper hierarchical relationships
     * 
     * Validates: Requirements 4.1, 4.2, 4.3
     */
    public function test_category_hierarchy_management()
    {
        $this->forAll(
            Generator\string(),
            Generator\string()
        )->then(function ($categoryName, $subcategoryName) {
            // Skip empty strings and very short names
            if (empty($categoryName) || empty($subcategoryName) || 
                strlen(trim($categoryName)) < 2 || strlen(trim($subcategoryName)) < 2) {
                return;
            }

            // Clear database for each iteration to avoid unique constraint issues
            Category::truncate();
            Subcategory::truncate();

            // Trim and limit names to fit database constraints
            $categoryName = substr(trim($categoryName), 0, 30);
            $subcategoryName = substr(trim($subcategoryName), 0, 40);

            // Create category
            $category = Category::create([
                'name' => $categoryName,
                // Slug will be auto-generated by Spatie Sluggable package
            ]);

            // Verify category creation
            $this->assertInstanceOf(Category::class, $category);
            $this->assertEquals($categoryName, $category->name);
            $this->assertNotEmpty($category->slug);
            $this->assertTrue($category->exists);

            // Create subcategory
            $subcategory = Subcategory::create([
                'category_id' => $category->id,
                'name' => $subcategoryName,
                // Slug will be auto-generated by Spatie Sluggable package
            ]);

            // Verify subcategory creation and relationship
            $this->assertInstanceOf(Subcategory::class, $subcategory);
            $this->assertEquals($subcategoryName, $subcategory->name);
            $this->assertEquals($category->id, $subcategory->category_id);
            $this->assertNotEmpty($subcategory->slug);
            $this->assertTrue($subcategory->exists);

            // Verify hierarchical relationship
            $this->assertTrue($category->subcategories->contains($subcategory));
            $this->assertEquals($category->id, $subcategory->category->id);

            // Verify slug uniqueness within the same table
            $duplicateCategory = new Category([
                'name' => $categoryName . ' Copy',
                // Don't set slug manually - let Sluggable package handle it
            ]);
            
            // Save and verify slug is different
            $duplicateCategory->save();
            $this->assertNotEquals($category->slug, $duplicateCategory->slug);
            // Sluggable package will create a unique slug, just verify it's not empty
            $this->assertNotEmpty($duplicateCategory->slug);
        });
    }

    /**
     * Property test for category slug generation uniqueness
     * Validates that slugs are properly generated and unique
     */
    public function test_category_slug_uniqueness()
    {
        $this->forAll(
            Generator\elements(['Electronics', 'Clothing', 'Books', 'Sports', 'Home']),
            Generator\int(1, 1000)
        )->then(function ($baseName, $suffix) {
            // Clear database for each iteration
            Category::truncate();

            $categoryName = $baseName . ' ' . $suffix;
            
            $category = Category::create([
                'name' => $categoryName,
                // Slug will be auto-generated by Spatie Sluggable package
            ]);

            // Verify slug is generated correctly
            $expectedSlug = \Illuminate\Support\Str::slug($categoryName);
            $this->assertEquals($expectedSlug, $category->slug);
            
            // Verify slug is unique in database
            $this->assertEquals(1, Category::where('slug', $category->slug)->count());
        });
    }

    /**
     * Property test for subcategory-category relationship integrity
     * Validates that subcategories are properly linked to categories
     */
    public function test_subcategory_category_relationship()
    {
        $this->forAll(
            Generator\elements(['T-Shirt', 'Jeans', 'Sneakers', 'Laptop', 'Phone']),
            Generator\elements(['Clothing', 'Electronics', 'Sports', 'Books'])
        )->then(function ($subcategoryName, $categoryName) {
            // Clear database for each iteration
            Category::truncate();
            Subcategory::truncate();

            // Create parent category
            $category = Category::create([
                'name' => $categoryName,
                // Slug will be auto-generated by Spatie Sluggable package
            ]);

            // Create subcategory
            $subcategory = Subcategory::create([
                'category_id' => $category->id,
                'name' => $subcategoryName,
                // Slug will be auto-generated by Spatie Sluggable package
            ]);

            // Verify relationship works both ways
            $this->assertEquals($category->id, $subcategory->category->id);
            $this->assertTrue($category->subcategories->contains($subcategory));
            
            // Verify we can access category through subcategory
            $retrievedCategory = $subcategory->category;
            $this->assertEquals($categoryName, $retrievedCategory->name);
            
            // Verify we can access subcategories through category
            $retrievedSubcategories = $category->subcategories;
            $this->assertTrue($retrievedSubcategories->contains($subcategory));
        });
    }
}